# Generated by Django 4.2 on 2026-09-28 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_indexedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('extracted_text', models.TextField()),
                ('faiss_index_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Indexed CV',
            },
        ),
    ]
