# Generated by Django 4.2 on 2026-10-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_indexedcv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexedCV',
        ),
        migrations.DeleteModel(
            name='IndexedJob',
        ),
    ]
