#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $USER_DB_NAME;
    CREATE DATABASE $JOB_DB_NAME;
    CREATE DATABASE $APPLICATION_DB_NAME;
    CREATE DATABASE $MATCHING_DB_NAME;
EOSQL