version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  user-service:
    build: ./User
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./User:/app
      - ./utils:/app/utils
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  job-service:
    build: ./Job
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Job:/app
      - ./utils:/app/utils
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  application-service:
    build: ./Application
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./Application:/app
      - ./utils:/app/utils
    ports:
      - "8002:8002"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  matching-service:
    build: ./Matching:/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    volumes:
      - ./Matching:/app
      - ./utils:/app/utils
      - ./media:/app/media
    ports:
      - "8003:8003"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build:
      context: ./Matching
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - ./Matching:/app
      - ./utils:/app/utils
      - ./static:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - redis
      - matching-service

  celery-beat:
    build:
      context: ./Matching
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A config beat --loglevel=info
    volumes:
      - ./Matching:/app
      - ./utils:/app/utils
      - ./static:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - redis
      - matching-service
