# Generated by Django 4.2 on 2025-07-03 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Job Seeker Profile',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='job_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('In_Progress', 'In Progress'), ('Interviewing', 'Interviewing'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
