# Generated by Django 4.2 on 2025-07-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_jobseekerprofile_alter_application_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
