# Generated by Django 4.2 on 2026-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_jobseekerprofile_extracted_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='unique_application_per_job'),
        ),
    ]
