# Generated by Django 4.2 on 2026-05-24 21:58

import application.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_unique_application_per_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='cvs/', validators=[application.validators.validate_pdf])),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User CV',
            },
        ),
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
    ]
